const SEED_DATA = [
    { name: "Amar", gamesPlayed: 102, goals: 53, wins: 57, ratings: { fitness: 3.6, control: 3.6, shooting: 3.6, defense: 3.6 } },
    { name: "JT", gamesPlayed: 68, goals: 46, wins: 32, ratings: { fitness: 3.6, control: 3.6, shooting: 3.6, defense: 3.6 } },
    { name: "Johann", gamesPlayed: 67, goals: 43, wins: 30.5 },
    { name: "Nico", gamesPlayed: 65, goals: 37, wins: 35 },
    { name: "Jarrad", gamesPlayed: 50, goals: 35, wins: 20, ratings: { fitness: 3.1, control: 3.1, shooting: 3.1, defense: 3.1 } },
    { name: "Duncan", gamesPlayed: 58, goals: 29, wins: 35 },
    { name: "Tim", gamesPlayed: 51, goals: 36, wins: 36, ratings: { fitness: 4.0, control: 4.0, shooting: 4.0, defense: 4.0 } },
    { name: "Weylu", gamesPlayed: 49, goals: 23, wins: 23 },
    { name: "Wafik", gamesPlayed: 35, goals: 11, wins: 17 },
    { name: "Derek", gamesPlayed: 31, goals: 1, wins: 15 },
    { name: "G", gamesPlayed: 26, goals: 28, wins: 13 },
    { name: "Zoran", gamesPlayed: 22, goals: 3, wins: 11 },
    { name: "Travers", gamesPlayed: 20, goals: 1, wins: 10 },
    { name: "Agge", gamesPlayed: 20, goals: 15, wins: 12 },
    { name: "Kristof", gamesPlayed: 16, goals: 15, wins: 8 },
    { name: "Josh", gamesPlayed: 14, goals: 14, wins: 7 },
    { name: "Greg", gamesPlayed: 14, goals: 4, wins: 4.5 },
    { name: "Figo", gamesPlayed: 13, goals: 25, wins: 9, ratings: { fitness: 4.5, control: 4.5, shooting: 4.5, defense: 4.5 } },
    { name: "Gino", gamesPlayed: 13, goals: 1, wins: 6.5 },
    { name: "Oz", gamesPlayed: 11, goals: 3, wins: 3.5 },
    { name: "Max", gamesPlayed: 10, goals: 3, wins: 5 },
    { name: "Dorian", gamesPlayed: 8, goals: 1, wins: 4 },
    { name: "Olly", gamesPlayed: 7, goals: 2, wins: 3.5 },
    { name: "Austin", gamesPlayed: 7, goals: 2, wins: 3.5 },
    { name: "Vin", gamesPlayed: 7, goals: 2, wins: 3.5 },
    { name: "Johnny", gamesPlayed: 5, goals: 5, wins: 4 },
    { name: "Drew", gamesPlayed: 4, goals: 6, wins: 3 },
    { name: "Sal", gamesPlayed: 4, goals: 5, wins: 2 },
    { name: "Jeff", gamesPlayed: 3, goals: 1, wins: 2 },
    { name: "Gabe D", gamesPlayed: 3, goals: 2, wins: 2 },
    { name: "Bruce", gamesPlayed: 3, goals: 1, wins: 1 },
    { name: "Gary", gamesPlayed: 3, goals: 1, wins: 1 },
    { name: "Hadi", gamesPlayed: 3, goals: 1, wins: 0 },
    { name: "Carter", gamesPlayed: 3, goals: 1, wins: 0 },
    { name: "Mike", gamesPlayed: 3, goals: 1, wins: 0 },
    { name: "Dante", gamesPlayed: 3, goals: 1, wins: 0 },
    { name: "Jonathan", gamesPlayed: 2, goals: 3, wins: 1 },
    { name: "Rachael", gamesPlayed: 2, goals: 0, wins: 1 },
    { name: "Anh", gamesPlayed: 2, goals: 0, wins: 1 },
    { name: "Santi", gamesPlayed: 1, goals: 2, wins: 0 },
    { name: "Italian", gamesPlayed: 1, goals: 2, wins: 0 },
    { name: "Carlos", gamesPlayed: 0, goals: 0, wins: 0, ratings: { fitness: 4.8, control: 4.8, shooting: 4.8, defense: 4.8 } },
    { name: "Jared", gamesPlayed: 4, goals: 0, wins: 2, ratings: { fitness: 3.6, control: 3.6, shooting: 3.6, defense: 3.6 } },
];

export default SEED_DATA;
